### ISSUE TITLE
function should exterm system on win32

### ISSUE THREAD

**Issue by bstaint** [KernelErr0r/bass-sys#1]
Tks this crate.

msvc x86 compile link error output like:
```
error LNK2019: 无法解析的外部符号 _BASS_Free，函数 __ZN53_$LT$bass..TBass$u20$as$u20$core..ops..drop..Drop$GT$4drop17h3
5a3f4d22b8c34e6E 中引用了该符号
error LNK2019: 无法解析的外部符号 _BASS_GetVersion，函数 __ZN4bass5TBass3new17hc4ec67e87fa95898E 中引用了该符号
```
function should exterm system。

**Comment by thatbakamono** [comment]
It works for me on Windows, have you tried downloading bass.dll from http://www.un4seen.com/ and then pasting in the lib folder located in your project root directory?

**Comment by bstaint** [comment]
Yes, i use toolchain default `nightly-i686-pc-windows-msvc`
x86_64-pc-windows-msvc it work,
x686-pc-windows-msvc will link error.

**Comment by thatbakamono** [comment]
Make sure you are using correct version of Bass. It seems like you are trying to link 64-bit version on the 32-bit toolchain.

**Comment by bstaint** [comment]
OK, tks answer.
