### ISSUE TITLE
bass_fxsetparams panic

### ISSUE THREAD

**Issue by jbrodriguez** [KernelErr0r/bass-sys#11]
i'm getting a panic when trying to set params like this 

```
        self.fx = bass_sys::BASS_ChannelSetFX(self.stream, bass_sys::BASS_FX_VOLUME, 0);
        let gain = 10_f64.powf(song.track_gain / 20.0);

        // pub struct BassFxVolumeParam {
        //     pub target: f32,
        //     pub current: f32,
        //     pub time: f32,
        //     pub curve: DWORD,
        // }
        println!("Gain: {}", gain);

        let params = bass_sys::BassFxVolumeParam {
            target: gain as f32,
            current: 0.0,
            time: 0.0,
            curve: 0,
        };

        println!("params: {:?}", params);
        println!("fx: {:?}", self.fx);

        let fxset = bass_sys::BASS_FxSetParameters(
            self.fx,
            &params as *const bass_sys::BassFxVolumeParam as *const c_void,
        );
```
the error is 

```
thread 'main' panicked at 'Failed to load the function.', /Users/<redacted>/.cargo/registry/src/github.com-1ecc6299db9ec823/bass-sys-2.2.2/src/functions.rs:90:1
```

any idea on how to fix it ?

**Comment by thatbakamono** [comment]
Did you download the library and place it in the correct directory? bass-sys doesn't automatically do this for you cause shipping pre-built dynamic libraries in Rust is tricky.

**Comment by TheChilliPL** [comment]
> Did you download the library and place it in the correct directory? bass-sys doesn't automatically do this for you cause shipping pre-built dynamic libraries in Rust is tricky.

Would it be possible for bass-sys to check whether the library is there at runtime and throw an error in the case it isn't?

**Comment by jbrodriguez** [comment]
> Did you download the library and place it in the correct directory? bass-sys doesn't automatically do this for you cause shipping pre-built dynamic libraries in Rust is tricky.

yep, i did, it works ok loading the main lib (libass.dylib) and the flac plugin (libbassflac.dylib) both located in /usr/local/lib

i can `BASS_StreamCreateFile` and even `BASS_ChannelPlay`, but if i try to `BASS_FxSetParameters` it panics

it would seem like the function doesn't exist ? but that function is built-in right, one doesn't need a plugin to use FX or do we ?

**Comment by thatbakamono** [comment]
> > Did you download the library and place it in the correct directory? bass-sys doesn't automatically do this for you cause shipping pre-built dynamic libraries in Rust is tricky.
> 
> Would it be possible for bass-sys to check whether the library is there at runtime and throw an error in the case it isn't?

It actually does, I forgot about this. 

https://github.com/thatbakamono/bass-sys/blob/e150a1f16468710da352b1ed7a89d9cf8791d281/src/functions.rs#L36-L48

**Comment by thatbakamono** [comment]
> > Did you download the library and place it in the correct directory? bass-sys doesn't automatically do this for you cause shipping pre-built dynamic libraries in Rust is tricky.
> 
> yep, i did, it works ok loading the main lib (libass.dylib) and the flac plugin (libbassflac.dylib) both located in /usr/local/lib
> 
> i can `BASS_StreamCreateFile` and even `BASS_ChannelPlay`, but if i try to `BASS_FxSetParameters` it panics
> 
> it would seem like the function doesn't exist ? but that function is built-in right, one doesn't need a plugin to use FX or do we ?

I'm honestly not sure but I'll look into it. What version of bass do you use?

**Comment by jbrodriguez** [comment]
> I'm honestly not sure but I'll look into it. What version of bass do you use?

i'm using the latest 2.4.17, the error comes from the binding macro https://github.com/thatbakamono/bass-sys/blob/master/src/macros.rs#L9

**Comment by thatbakamono** [comment]
I found out what the issue is. I mistyped one of the names.

https://github.com/thatbakamono/bass-sys/blob/e150a1f16468710da352b1ed7a89d9cf8791d281/src/functions.rs#L295-L296

It should be upper case `FX` in both cases, that's why it couldn't find that function. I'll soon push the commit and release a new version.

**Comment by TheChilliPL** [comment]
Should be worth it adding tests so that this stuff is caught in compile time

**Comment by jbrodriguez** [comment]
> It should be upper case `FX` in both cases, that's why it couldn't find that function. I'll soon push the commit and release a new version.

cool stuff man ! thanks a lot !

**Comment by thatbakamono** [comment]
New version is available.

**Comment by thatbakamono** [comment]
> Should be worth it adding tests so that this stuff is caught in compile time

It 100% could be done, I have two ideas at the moment how this could be implemented (either smart by manually inspecting symbols in the library or just by brute force - by trying to load all the functions and catching panics if there are any). I might do it in the future as it seems interesting.
