### ISSUE TITLE
DeviceInfo fields are not public

### ISSUE THREAD

**Issue by ayyEve** [KernelErr0r/bass-sys#7]
makes it a bit hard to actually use devices :P

**Comment by thatbakamono** [comment]
To be honest, I don't even remember why I didn't make most of fields public in the first place, most likely I wanted to make proper getter/setters but never did so.

**Comment by ayyEve** [comment]
lol fair enough, i can do a pr to make everything public if you want

**Comment by thatbakamono** [comment]
Too bad I didn't read it earlier because I already did that and it's available on master, I will publish it on crates.io once I figure out one more thing (atm I use Vec for FAM and that's... incorrect, I don't know why I did that).
